name: Ci Dev Fetti

on:
  push:
    branches:
      - dev  

jobs:
  build-client:
    runs-on: ubuntu-latest 

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      # Step 3: Install client dependencies
      - name: Install client dependencies
        run: |
          npm install


  deploy-client:
    runs-on: ubuntu-latest
    needs: build-client  
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_DROPLET }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/fetti-client
            git pull origin dev
            git checkout dev
            npm install
            npm run build  
            pm2 restart client

      - name: Notify Discord (Success)
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Deployment to Dev of Client was successful!"}' \
          ${{ secrets.DEV_WEBHOOK }}

      - name: Notify Discord (Failure)
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Deployment to Dev of Client failed!"}' \
          ${{ secrets.DEV_WEBHOOK }}