name: Deploy Frontend to Dev Server

on:
  push:
    branches:
      - dev

jobs:
  deploy-frontend-dev:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5. Deploy to dev server via SSH
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/nextjs-app
            git reset --hard
            git pull origin dev
            npm ci
            npm run build
            pm2 restart client-dev || pm2 start npm --name "client-dev" -- start

      # 6. Notify Discord if success
      - name: Notify Discord (Success)
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Deployment to Dev of Client was successful!"}' \
          ${{ secrets.DEV_WEBHOOK }}

      # 7. Notify Discord if failure
      - name: Notify Discord (Failure)
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Deployment to Dev of Client failed!"}' \
          ${{ secrets.DEV_WEBHOOK }}
